### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JiangHaiYang01** [DylanCaiCoding/ViewBindingKtx#1]
class LogInAct : AppCompatActivity() {

    private val binding: ActivityLoginBinding by inflate()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
//        binding.apply {
//            fuck .text = "fuck you"
//        }
    }
}

这样是加载不出来的 方法不执行 setContentView

只有执行了 apply 才会生效 。 感觉不是你的bug 像是 datbinding 的bug

**Comment by DylanCaiCoding** [comment]
是的， binding 用到了才会执行 setContentView() 方法。对于这种不会第一时间用到 binding 的情况，可以在构造函数里传布局或手动调用 setContentView(binding.root) 设一次布局。
