### ISSUE TITLE
可以和Xpopup结合使用吗

### ISSUE THREAD

**Issue by eastblack** [DylanCaiCoding/ViewBindingKtx#11]

**Comment by DylanCaiCoding** [comment]
XPopup 自定义弹窗本质是一个自定义 View，新版本支持在自定义 View 中使用，你可以查看 [Wiki](https://github.com/DylanCaiCoding/ViewBindingKtx/wiki/%E4%BD%BF%E7%94%A8%E6%8B%93%E5%B1%95%E5%87%BD%E6%95%B0) 中的用法
