### ISSUE TITLE
用ON_DESTROY代替onDestroyView始终还是有问题的

### ISSUE THREAD

**Issue by svenjung** [DylanCaiCoding/ViewBindingKTX#13]
你结合fragment-navigation试下就知道了

**Comment by DylanCaiCoding** [comment]
viewLifecycleOwner 的 ON_DESTROY 时机是 onDestroyView，之前有打印生命周期测过。我试了下使用 Navigation 没发现问题。请问你是怎么使用的？遇到了怎样的问题？

**Comment by svenjung** [comment]
> viewLifecycleOwner 的 ON_DESTROY 时机是 onDestroyView，之前有打印生命周期测过。我试了下使用 Navigation 没发现问题。请问你是怎么使用的？遇到了怎样的问题？

你结合navigation试试就知道了

**Comment by svenjung** [comment]
ON_DESTROY onDestroyView 和 onDestroy 都会调

**Comment by DylanCaiCoding** [comment]
> ON_DESTROY onDestroyView 和 onDestroy 都会调

试了下没测出报错，所以想问下你是遇到了什么问题？

三个方法是都会回调，lifecycle 观察的会比 Fragment 的早回调，等效于下面的逻辑。

```kotlin
override fun onDestroyView() {
  _binding = null
  super.onDestroyView()
}
```

**Comment by svenjung** [comment]
navigation 中 Fragment A 启动B，B返回A，A再启动B，B返回A。A就出问题了

**Comment by DylanCaiCoding** [comment]
> navigation 中 Fragment A 启动B，B返回A，A再启动B，B返回A。A就出问题了

感谢反馈，已找到原因，viewLifecycle 在 onDestroyView 后没有再回调，是我对 viewLifecycleOwner 的理解有误，以为是不变的，查看源码发现在 performCreateView 会创建一个新的 FragmentViewLifecycleOwner 对象。所以不能只观察一次，要每次创建 binding 对象要重新 observe。

**Comment by DylanCaiCoding** [comment]
已发布 1.1.1 版本修复了该问题
