### ISSUE TITLE
libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by chen3441251** [DylanCaiCoding/ViewBindingKTX#15]
![image](https://user-images.githubusercontent.com/16670488/113800166-109d7380-9789-11eb-891b-d19e121710e7.png)
![image](https://user-images.githubusercontent.com/16670488/113800257-36c31380-9789-11eb-8826-a90984bd7b62.png)

找不出问题到底在哪

**Comment by DylanCaiCoding** [comment]
请问下基类是怎么写的，泛型定义了什么？有没什么继承关系？

**Comment by chen3441251** [comment]
> 请问下基类是怎么写的，泛型定义了什么？有没什么继承关系？

这个报错是Fragment基类报错的，Activity基类是正常的

fragment有两层继承关系如图所示：xxxFragment--->SupportBaseFragment-->BaseFragment

![image](https://user-images.githubusercontent.com/16670488/113807089-0df54b00-9796-11eb-88f2-9de79b5f5264.png)
![image](https://user-images.githubusercontent.com/16670488/113807175-38df9f00-9796-11eb-8d73-5a23ff6fd675.png)


在baseFragment的onCreateView函数里面调用inflateBindingWithGeneric(layoutInflater)就报错了

**Comment by DylanCaiCoding** [comment]
我发了 1.1.3 版本修复该问题，但是现在不能发到 jcenter 了，五月要停用 jcenter。需要在 project 的 build.gradle 添加下面的 maven url 才能使用 1.1.3 版本：

```groovy
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/dylancai/maven' }
    }
}
```

我近期会发布到 mavencenter ，到时可以把这行去掉。

**Comment by chen3441251** [comment]
确实好了

**Comment by DylanCaiCoding** [comment]
> 确实好了，大佬修复了哪里。早上研究了半天没找到哪里出错了

之前在遍历泛型那里只测出报 NoSuchMethodException，当时只 catch 这个异常，没想到还可能会报类型转换异常，都 catch 了就行了。类型转换异常的原因好像是泛型的泛型不能强转成 Class，上面的 A 泛型里还有个 VB 泛型，这个被遍历出来强转成 Class 导致报错。

另外不太建议 BaseFragment 指定 Activity，Fragment 可能会用在多个地方的

**Comment by chen3441251** [comment]
> 另外不太建议 BaseFragment 指定 Activity，Fragment 可能会用在多个地方的

好的
