### ISSUE TITLE
Fragment能不能提供 inflate

### ISSUE THREAD

**Issue by zwonb** [DylanCaiCoding/ViewBindingKTX#16]
想弄个类似这样的 `val binding: ViewBinding by inflate<VB>()`

**Comment by DylanCaiCoding** [comment]
可以提供，不过这样封装只能调用 `FragmentHomeBinding.inflate(layoutInflater)`，和 
 `FragmentHomeBinding.inflate(layoutInflater, parent, fale)` 所实现的效果可能会不一样。而且还要重写 `onCreateView` 方法，代码量会多不少。之前有考虑过提供下面的用法：

```kotlin
class HomeFragment : Fragment() {
  val binding: FragmentHomeBinding by binding(Method.INFLATE)

  override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?)=
    binding.root

  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState)
    binding.apply { 
      TODO()
    }
  }
}
```

个人想了很久觉得不太推荐这么来用就去掉了，觉得不如现在的用法。有需要的话是可以加回来，不过想问下为什么想要通过 inflate 来调用？

**Comment by zwonb** [comment]
在自定义的baseFragment里面需要动态添加view需要用到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午4:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DylanCaiCoding/ViewBindingKTX] Fragment能不能提供 inflate (#16)





 
可以提供，不过这样封装只能调用 FragmentHomeBinding.inflate(layoutInflater)，和
 FragmentHomeBinding.inflate(layoutInflater, parent, fale) 所实现的效果可能会不一样。而且还要重写 onCreateView 方法，代码量会多不少。之前有考虑过提供下面的用法：
 class HomeFragment : Fragment() {   val binding: FragmentHomeBinding by binding(Method.INFLATE)   override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?)=     binding.root   override fun onViewCreated(view: View, savedInstanceState: Bundle?) {     super.onViewCreated(view, savedInstanceState)     binding.apply {        TODO()     }   } }
 
个人想了很久觉得不太推荐这么来用就去掉了，觉得不如现在的用法。有需要的话是可以加回来，不过想问下为什么想要通过 inflate 来调用？

**Comment by DylanCaiCoding** [comment]
我发了 1.1.4 版本增加了该用法，目前还没转 mavencenter，而  jcenter 不能发新版了，要添加个 maven url：
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/dylancai/maven' }
    }
}
```
