### ISSUE TITLE
请问最新版1.1.4什么时候能迁移到maven仓库

### ISSUE THREAD

**Issue by chen3441251** [DylanCaiCoding/ViewBindingKTX#18]

**Comment by DylanCaiCoding** [comment]
抱歉，前段时间加班很多还没弄好，mavencenter 的 gradle 配置还有些问题，资料偏少而且很多的比较老。现在工作稍微缓和了些，我会尽快处理。

**Comment by DylanCaiCoding** [comment]
非常抱歉，迁移 mavencenter 还没搞掂，先改用 Jitpack 了，README 和 Wiki 已更新，补充了使用示例，可以先看下。不过现在的依赖有点长，后续还是会发到 mavencenter，到时只需换个依赖。

**Comment by xmt328** [comment]
请问下还考虑迁移到mavencenter嘛？jitpack国内没有镜像，特殊时期的访问容易挂

**Comment by DylanCaiCoding** [comment]
> 请问下还考虑迁移到mavencenter嘛？jitpack国内没有镜像，特殊时期的访问容易挂

目前不考虑了，因为之前花过一个多月的业余时间没搞掂，不知道还会弄多久。个人现在还有两三个库想分享，每一个都要实现所构思的用法并测试验证、考虑更多的使用场景和简化用法、优化为尽可能简洁的代码、写博客把封装思路讲清楚，这些工作都会花掉个人大量的时间，暂时不考虑迁移 mavencenter。
