### ISSUE TITLE
viewbinding-base:1.2.0 中 bindViewWithGeneric(view: View) 反射失败

### ISSUE THREAD

**Issue by dasamanren** [DylanCaiCoding/ViewBindingKTX#19]
![image](https://user-images.githubusercontent.com/6468888/119322831-9f6e3d00-bcb0-11eb-98bd-6801f42dd355.png)

参数类型错了，希望可以修改一下

**Comment by DylanCaiCoding** [comment]
感谢反馈，已发 1.2.1 版本修改该问题，并且也让 viewbinding-base 支持使用 DataBinding 时自动设置 lifecycleOwner。想问下在什么场景下封装反射 bind 方法？个人封装到基类都是反射 inflate 方法，这个 bind 方法仅仅是保留着并没有用过，所以没注意到这个问题。

**Comment by dasamanren** [comment]
是在ViewPager + Fragment的时候，避免Fragment销毁又创建，不知道现在是不是不需要这样写了？
![image](https://user-images.githubusercontent.com/6468888/120156621-b9fe6400-c224-11eb-8f1d-ccc8be21edd1.png)
