### ISSUE TITLE
使用抽屉时，怎么获取menu列表中控件的id?

### ISSUE THREAD

**Issue by zouchuqu** [DylanCaiCoding/ViewBindingKTX#20]
使用抽屉时，怎么获取menu列表中控件的id?

**Comment by DylanCaiCoding** [comment]
是说 NavigationView 吗？我迟点增加一个 setHeaderView() 方法

**Comment by DylanCaiCoding** [comment]
已发 1.2.2 版本增加 NavigationView.setHeaderView() 方法，还有其它需求可以继续补充，我会继续完善的
