### ISSUE TITLE
binding接收的泛型不能是泛型

### ISSUE THREAD

**Issue by BravestSnail** [DylanCaiCoding/ViewBindingKTX#22]
`abstract class BaseActivity<VB: ViewBinding> : AppCompatActivity() {
    val binding by binding<VB>()`
我想要通过这样的方式去定义一个BaseActivity时，警告**Cannot use 'VB' as reified type parameter. Use a class instead**
`abstract class BaseActivity<VB: ViewBinding> : AppCompatActivity() {
    val binding:VB by binding()`
这样的写法也会给同样的警告

**Comment by DylanCaiCoding** [comment]
是的，这个属性委托不能直接用于基类，想封装到基类需要用另一种方式，可查看 [改造基类](https://github.com/DylanCaiCoding/ViewBindingKTX/wiki/%E6%94%B9%E9%80%A0%E5%9F%BA%E7%B1%BB-(Kotlin)) 的 Wiki 文档
