### ISSUE TITLE
布局如果出现了问题，无法找到问题点

### ISSUE THREAD

**Issue by mikaelzero** [DylanCaiCoding/ViewBindingKTX#24]
异常都是报  There is no generic of ViewBinding

直接把原有的异常给覆盖了

**Comment by DylanCaiCoding** [comment]
感谢反馈，已发 1.2.3 版本修复该问题，想问下是怎么样的布局问题能过编译却运行报错？

**Comment by mikaelzero** [comment]
比如?colorWhite  这种设置在主题里的颜色值之类的
