### ISSUE TITLE
fragment的nullPointException错误

### ISSUE THREAD

**Issue by mikaelzero** [DylanCaiCoding/ViewBindingKTX#25]
<img width="805" alt="WX20210630-100908@2x" src="https://user-images.githubusercontent.com/6696343/123891287-49fe0d80-d98b-11eb-966c-ea52921300eb.png">

这是代码中使用

//这是一个异步
 Pan.loadBitmap(requireContext(), homeIndexBean!!.weekGift.imgUrl) {
            binding.freeWeekIv.setImageBitmap(it)//这行报错
            binding.blurLayout.setBlurredView(binding.freeWeekIv)
        }

下面是BaseFragment中的使用方法

private var _binding: VB? = null
    val binding: VB get() = _binding!!

_binding = inflateBindingWithGeneric(layoutInflater)

**Comment by DylanCaiCoding** [comment]
应该是异步回调时 Fragment 被销毁了，可以在 onDestoryView 解除订阅。或者回调时判断下 binding 的状态，在 BaseFragment 增加以下方法：

```kotlin
val isBindingAvaiable get() = _binding != null
```

回调时判断下 binding 是不是可用

```kotlin
if (isBindingAvaiable) {
  binding.freeWeekIv.setImageBitmap(it)
  binding.blurLayout.setBlurredView(binding.freeWeekIv)
}
```
