### ISSUE TITLE
多层继承Activity fragment 怎么封装?

### ISSUE THREAD

**Issue by marren06** [DylanCaiCoding/ViewBindingKTX#26]
![image](https://user-images.githubusercontent.com/17778482/123918133-27351e80-d9b6-11eb-8201-143e3d466990.png)
![image](https://user-images.githubusercontent.com/17778482/123918170-2ef4c300-d9b6-11eb-93f7-c18288181263.png)
![image](https://user-images.githubusercontent.com/17778482/123918189-34520d80-d9b6-11eb-8c57-04d73afb4445.png)
你好作者，

    请问我这种mvp模式下的多层继承怎么封装ViewBinding ?

   BaseMvpActivity 下是没有布局文件  而 BaseMvpTitleActivity  有封装了Toorbar的布局   

 按照你的封装基类方法  泛型怎么写？

**Comment by DylanCaiCoding** [comment]
建议是新增基类，这样不会影响到原有的代码。新增 `BindingActivity<VB>` 继承 `BaseActivity`、`BindingMvpActivity<VB, V, P>` 继承 `BaseMvpActivity`、`BindingMvpTitleActivity<VB, V, P>` 继承 `BaseMvpTitleActivity`

**Comment by marren06** [comment]
> 建议是新增基类，这样不会影响到原有的代码。新增 `BindingActivity<VB>` 继承 `BaseActivity`、`BindingMvpActivity<VB, V, P>` 继承 `BaseMvpActivity`、`BindingMvpTitleActivity<VB, V, P>` 继承 `BaseMvpTitleActivity`

明白了，感谢指点！
