### ISSUE TITLE
proguard.ParseException: Expecting separator ';' before 'inflate'

### ISSUE THREAD

**Issue by amd110** [DylanCaiCoding/ViewBindingKTX#27]
大神 我在开启混淆后打包报错
java.io.IOException: proguard.ParseException: Expecting separator ';' before 'inflate' in line 293 of file xxx

-keepclassmembers public class * implements androidx.viewbinding.ViewBinding {
  public static * inflate(android.view.LayoutInflater);
  public static * inflate(android.view.LayoutInflater, android.view.ViewGroup, boolean);
  public static * bind(android.view.View);
}

**Comment by DylanCaiCoding** [comment]
混淆规则没发现问题，需要看下那个文件 293 行报错的代码是什么

**Comment by amd110** [comment]
我改成这样就没问题
-keepclassmembers class * implements androidx.viewbinding.ViewBinding {
    public static ** bind(***);
    public static ** inflate(...);
}
