### ISSUE TITLE
使用基类 Fragment封装示例是不是有问题?

### ISSUE THREAD

**Issue by nicelyjust** [DylanCaiCoding/ViewBindingKTX#29]
[使用基类](https://github.com/DylanCaiCoding/ViewBindingKTX/wiki/%E6%94%B9%E9%80%A0%E5%9F%BA%E7%B1%BB-(Kotlin)#%E4%B8%8D%E4%BD%BF%E7%94%A8%E5%8F%8D%E5%B0%84)

Fragment的主构造函数那个地方?

**Comment by DylanCaiCoding** [comment]
感谢反馈，已经改过来了
