### ISSUE TITLE
多布局的adpater如何封装呢

### ISSUE THREAD

**Issue by githeer** [DylanCaiCoding/ViewBindingKtx#3]
能加个多布局的适用例子不

**Comment by githeer** [comment]
我用的也是BRVAH

**Comment by DylanCaiCoding** [comment]
周末会写篇文章来补充 BRVAH 封装使用 ViewBinding，到时一起讲下 BRVAH 多布局的情况。

**Comment by githeer** [comment]
好的，文章地址在哪里我当时候去看看

**Comment by githeer** [comment]
对了，你的minSdkVersion  21版本太高了，调低一点，更好的兼容

**Comment by DylanCaiCoding** [comment]
> 对了，你的minSdkVersion 21版本太高了，调低一点，更好的兼容

好的，今晚应该会发个测试版来适配 BRVAH，到时告诉你怎么用。讲解封装思路的文章周末写，发了会通知你。

**Comment by DylanCaiCoding** [comment]
目前对 BRVAH 进行了适配，添加依赖：

```kotlin
implementation 'com.dylanc:viewbinding-brvah-ktx:1.1.0-alpha'
```

在适配器重写 createBaseViewHolder() 方法，创建时调用 BaseViewHolder#withBinding() 方法进行处理，然后就能通过 holder.getViewBinding() 来使用 ViewBinding 了。

```kotlin
const val ITEM_TYPE_FOO = 1
const val ITEM_TYPE_TEXT = 2

class FooAdapter : BaseMultiItemQuickAdapter<MultiItemEntity, BaseViewHolder>() {

  init {
    addItemType(ITEM_TYPE_FOO, R.layout.item_foo)
    addItemType(ITEM_TYPE_TEXT, R.layout.item_text)
  }

  override fun createBaseViewHolder(parent: ViewGroup, layoutResId: Int): BaseViewHolder {
    val viewHolder = super.createBaseViewHolder(parent, layoutResId)
    return when (layoutResId) {
      R.layout.item_foo -> viewHolder.withBinding(ItemFooBinding::bind)
      R.layout.item_text -> viewHolder.withBinding(ItemTextBinding::bind)
      else -> throw IllegalStateException()
    }
  }

  override fun convert(holder: BaseViewHolder, item: MultiItemEntity) {
    when (item.itemType) {
      ITEM_TYPE_FOO -> holder.getViewBinding<ItemFooBinding>()
        .apply {
          TODO()
        }
      ITEM_TYPE_TEXT -> holder.getViewBinding<ItemTextBinding>()
        .apply {
          TODO()
        }
    }
  }
}
```

**Comment by jiqianwen** [comment]
> 目前对 BRVAH 进行了适配，添加依赖：
> 
> ```kotlin
> implementation 'com.dylanc:viewbinding-brvah-ktx:1.1.0-alpha'
> ```
> 
> 在适配器重写 createBaseViewHolder() 方法，创建时调用 BaseViewHolder#withBinding() 方法进行处理，然后就能通过 holder.getViewBinding() 来使用 ViewBinding 了。
> 
> ```kotlin
> const val ITEM_TYPE_FOO = 1
> const val ITEM_TYPE_TEXT = 2
> 
> class FooAdapter : BaseMultiItemQuickAdapter<MultiItemEntity, BaseViewHolder>() {
> 
>   init {
>     addItemType(ITEM_TYPE_FOO, R.layout.item_foo)
>     addItemType(ITEM_TYPE_TEXT, R.layout.item_text)
>   }
> 
>   override fun createBaseViewHolder(parent: ViewGroup, layoutResId: Int): BaseViewHolder {
>     val viewHolder = super.createBaseViewHolder(parent, layoutResId)
>     return when (layoutResId) {
>       R.layout.item_foo -> viewHolder.withBinding(ItemFooBinding::bind)
>       R.layout.item_text -> viewHolder.withBinding(ItemTextBinding::bind)
>       else -> throw IllegalStateException()
>     }
>   }
> 
>   override fun convert(holder: BaseViewHolder, item: MultiItemEntity) {
>     when (item.itemType) {
>       ITEM_TYPE_FOO -> holder.getViewBinding<ItemFooBinding>()
>         .apply {
>           TODO()
>         }
>       ITEM_TYPE_TEXT -> holder.getViewBinding<ItemTextBinding>()
>         .apply {
>           TODO()
>         }
>     }
>   }
> }
> ```

这混淆规则怎么加，混淆之后会报错ViewType: $viewType found layoutResId，please use addItemType() first!

**Comment by DylanCaiCoding** [comment]
> 这混淆规则怎么加，混淆之后会报错ViewType: $viewType found layoutResId，please use addItemType() first!

需要混淆规则的会自动加，而且 withBinding 方法没用反射可以直接混淆。

**Comment by NeVaDaAAA** [comment]
请问2.0.1这种多布局形式改如何写呢 我看作者您删除了下面这段代码
![飞书20220210-095312](https://user-images.githubusercontent.com/20659340/153322004-04a969aa-bcb8-412e-bb86-2126134fb241.png)

**Comment by DylanCaiCoding** [comment]
> 请问2.0.1这种多布局形式改如何写呢 我看作者您删除了下面这段代码 ![飞书20220210-095312](https://user-images.githubusercontent.com/20659340/153322004-04a969aa-bcb8-412e-bb86-2126134fb241.png)

是的，因为想到了更好的封装思路，所以把这原来的用法删了。

我把上面的多布局示例代码改成新版用法：

```kotlin
const val ITEM_TYPE_FOO = 1
const val ITEM_TYPE_TEXT = 2

class FooAdapter : BaseMultiItemQuickAdapter<MultiItemEntity, BaseViewHolder>() {

  init {
    addItemType(ITEM_TYPE_FOO, R.layout.item_foo)
    addItemType(ITEM_TYPE_TEXT, R.layout.item_text)
  }

  override fun convert(holder: BaseViewHolder, item: MultiItemEntity) {
    when (item.itemType) {
      ITEM_TYPE_FOO -> 
        holder.getBinding(ItemFooBinding::bind).apply {
          TODO()
        }
      ITEM_TYPE_TEXT -> 
        holder.getBinding(ItemTextBinding::bind).apply {
          TODO()
        }
    }
  }
}
```

无需再重写创建 ViewHolder 的方法就能获取 binding 了，方便很多。新封装的思路我迟点会再分享篇文章。

如果项目已经有很多地方用了老的方案，你可以保留 `viewbinding-brvah` 的版本为 1.x，把[这个类的源码](https://github.com/DylanCaiCoding/ViewBindingKTX/blob/master/viewbinding-brvah/src/main/java/com/dylanc/viewbinding/brvah/BaseViewHolderUtil.kt)拷过去用。

**Comment by NeVaDaAAA** [comment]
好的 谢谢作者
