### ISSUE TITLE
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

### ISSUE THREAD

**Issue by Chen-Xi-g** [DylanCaiCoding/ViewBindingKTX#32]
我在使用的时候出现这个问题，它提示我以下错误信息：
![image](https://user-images.githubusercontent.com/37918545/133092939-6df30eb7-13cd-4125-a911-22c215f462b2.png)
`Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option`
但是我运行的时候他没有任何问题。
而且在app -> build.gradle 中添加了以下代码，并没有什么用。
![image](https://user-images.githubusercontent.com/37918545/133093108-6dd7c541-f2d6-4a4e-a08a-26102d12dc72.png)

**Comment by DylanCaiCoding** [comment]
你到设置里把 Target JVM version 改为 1.8 试下。

![image](https://user-images.githubusercontent.com/23648286/133101411-4a78007e-bed8-4ac6-9bfc-2618e42cc2a7.png)
