### ISSUE TITLE
在android 11 level 30的某些机型上有"Fragment " + this + " did not return a View from onCreateView() or this was called before onCreateView().”异常。

### ISSUE THREAD

**Issue by censhengde** [DylanCaiCoding/ViewBindingKTX#37]

**Comment by censhengde** [comment]
附：我实在onActivityCreated方法中第一次引用ViewBinding字段的

**Comment by DylanCaiCoding** [comment]
看描述是使用属性委托的用法吧，这是通过 Fragment 构造函数传入布局去 onCreateView() 的，按理来说只要布局没有漏传应该不会出现这个问题才对。有没有完整点的代码来康康吗？

**Comment by censhengde** [comment]
> 看描述是使用属性委托的用法吧，这是通过 Fragment 构造函数传入布局去 onCreateView() 的，按理来说只要布局没有漏传应该不会出现这个问题才对。有没有完整点的代码来康康吗？

排查出来的，不是库的问题，是fragment状态问题，我在异步回调中使用binding操作了视图，而此时fragment已经销毁。

**Comment by DylanCaiCoding** [comment]
已发布 1.2.6 版本优化该报错信息，在 Fragment 销毁后获取 binding 对象会报 "The binding property has been destroyed" 方便排查问题。
