### ISSUE TITLE
关于自定义布局

### ISSUE THREAD

**Issue by 211885646** [DylanCaiCoding/ViewBindingKtx#4]
如果是带有xml的自定义布局该怎么封装呢~~~好像这么搞的人不是很多,但是我还是想请教一下

**Comment by DylanCaiCoding** [comment]
自定义布局是指自定义控件吗？

**Comment by 211885646** [comment]
对对&nbsp; 自定义控件那种绑定了xml的&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DylanCaiCoding/ViewBindingKtx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 下午5:04
收件人:&nbsp;"DylanCaiCoding/ViewBindingKtx"<ViewBindingKtx@noreply.github.com&gt;;
抄送:&nbsp;"想当然"<211885646@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DylanCaiCoding/ViewBindingKtx] 关于自定义布局 (#4)





 
自定义布局是指自定义控件吗？

**Comment by githeer** [comment]
就比如recycleview 添加了一个headview   head要绑定数据，这个能viewbinding封装吗

**Comment by DylanCaiCoding** [comment]
新版本支持了自定义 View 的用法，可以点击 [Wiki](https://github.com/DylanCaiCoding/ViewBindingKtx/wiki/%E4%BD%BF%E7%94%A8%E6%8B%93%E5%B1%95%E5%87%BD%E6%95%B0) 进行查看。
