### ISSUE TITLE
文档有个错误

### ISSUE THREAD

**Issue by ChawLoo** [DylanCaiCoding/ViewBindingKTX#41]
![image](https://user-images.githubusercontent.com/26214519/152748105-2e3f5fc1-b144-4c36-8edb-2d1ba1181f7b.png)

**Comment by DylanCaiCoding** [comment]
其实不是错误，Fragment 有个 getLayoutInflater() 方法，不过直接取方法参数的话代码阅读性是会好点。感谢反馈，文档已修改。
