### ISSUE TITLE
tools7.1.1开启混淆后崩溃

### ISSUE THREAD

**Issue by ccominghome** [DylanCaiCoding/ViewBindingKTX#43]
com.android.tools.build:gradle 7.1.1 开启混淆后崩溃,libcore.reflect.TypeVariableImpl cannot be cast to java.lang.Class

**Comment by DylanCaiCoding** [comment]
我建个项目测了 7.1.1 和 7.2 都能正常运行哦

**Comment by ccominghome** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/19590764/155946464-c46c2460-251d-4c17-b3ba-54fc6bb52c9d.png">
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19590764/155946588-31d26001-eaf4-4f86-aea2-013b56587968.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/19590764/155946809-e934538d-fdc4-47cf-8c16-9d6c363f6512.png">
<img width="924" alt="image" src="https://user-images.githubusercontent.com/19590764/155946974-16d75651-93c9-4ce9-b605-f399471d0c4b.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/19590764/155947086-1203cd40-92d1-4bcb-96c3-95dc1f649f1d.png">

kotlin用的哪个版本,我在demo上这样改是可以复现的

**Comment by ccominghome** [comment]
> 我建个项目测了 7.1.1 和 7.2 都能正常运行哦

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/19590764/155954868-40f1527a-84dc-492a-b98e-472365ced50b.png">
报这几个错

**Comment by DylanCaiCoding** [comment]
感谢测试反馈，我在 Demo 上测了是适配器内敛的问题，其它反射都是正常的。出问题的只是下面的用法，你是不是在项目这么用了？

```kotlin
private val adapter = simpleStringListAdapter<ItemFooBinding> {
  textView.text = it
}
```

项目代码已修改，你升到 7.1.1 应该能正常运行 Demo 了。没别的问题话我明天发个版修复该问题。

**Comment by DylanCaiCoding** [comment]
已发 2.0.2 版本修复该问题

**Comment by ccominghome** [comment]
> 感谢测试反馈，我在 Demo 上测了是适配器内敛的问题，其它反射都是正常的。出问题的只是下面的用法，你是不是在项目这么用了？
> 
> ```kotlin
> private val adapter = simpleStringListAdapter<ItemFooBinding> {
>   textView.text = it
> }
> ```
> 
> 项目代码已修改，你升到 7.1.1 应该能正常运行 Demo 了。没别的问题话我明天发个版修复该问题。

排查到了,不是因为这个,项目中使用了hilt,升级到2.41就好了
