### ISSUE TITLE
加载自定义底部导航栏崩溃

### ISSUE THREAD

**Issue by panyy** [DylanCaiCoding/ViewBindingKTX#45]

**Comment by panyy** [comment]
![微信截图_20220407104222](https://user-images.githubusercontent.com/5070279/162109936-eaebbfe2-193b-4e00-96db-c609d7add9a9.png)

**Comment by DylanCaiCoding** [comment]
使用的是最新版吗？新版应该不会报 InvocationTargetException

**Comment by panyy** [comment]
用的最新的2.0.4版

**Comment by panyy** [comment]
我发现布局里有com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx这个自定义view不行，其他自定义view没有问题

**Comment by DylanCaiCoding** [comment]
这里报错是反射到了泛型，但是调用 `ActivityMainBinding.inflate(layoutInflater)`  时崩溃了，而反射会把异常信息包装成 InvocationTargetException。你手动调下 `ActivityMainBinding.inflate(layoutInflater)` 看下报的什么异常，这才是真正导致崩溃的原因。

之前有个人反馈类似的问题是少加了个控件的配置，感觉你的也是这个原因。

**Comment by panyy** [comment]
![微信截图_20220407122602](https://user-images.githubusercontent.com/5070279/162120064-7b19496c-4392-45cf-be89-89f7ed19db02.png)
这样引入就没有问题，库里用的material的1.4，我项目用的1.3，然后就报错了。

**Comment by DylanCaiCoding** [comment]
发了 2.0.5 版本，不会再报 InvocationTargetException，会抛出具体的异常。另外把 material 的版本降为 1.3.0，1.4.0 好像是有点高
