### ISSUE TITLE
关于include

### ISSUE THREAD

**Issue by BugRui** [DylanCaiCoding/ViewBindingKtx#5]
您好，请教一个问题，在布局中使用了include，ViewBindingKtx是如何处理的？

**Comment by DylanCaiCoding** [comment]
> 您好，请教一个问题，在布局中使用了include，ViewBindingKtx是如何处理的？

本库没对 include 的布局进行封装，因为原本的用法已经足够简单了。可以大概和你说下，有两种使用情况：

1. include 的布局不含 merge 标签。

首先要给 include 的布局增加一个 id。

```xml
<include
    android:id="@+id/toolbar"
    layout="@layout/layout_toolar" />
```

这样就可以通过父布局的绑定对象拿到子布局的绑定对象了。

```kotlin
binding.apply {
      toolbar.tvTitle.text = title
}
```

2. include 的布局包含 merge 标签。

这和前面用法有点不一样，不能给 include 标签增加 id。

然后用子布局的 bind() 方法传入父布局的根布局去获取绑定对象。

```kotlin
val mergeBinding = LayoutMergeBinding.bind(binding.root)
```

**Comment by BugRui** [comment]
跟感谢您的回答，get到了
