### ISSUE TITLE
为啥ViewBindingUtil 找不到引用了呢

### ISSUE THREAD

**Issue by conscious01** [DylanCaiCoding/ViewBindingKTX#50]
<img width="1648" alt="Screenshot 2022-04-25 at 5 11 40 PM" src="https://user-images.githubusercontent.com/16432956/165058611-0642878a-f39b-4a12-876b-8d5618f1b700.png">
<img width="1660" alt="Screenshot 2022-04-25 at 5 11 58 PM" src="https://user-images.githubusercontent.com/16432956/165058632-ce354335-0b5f-4728-a9dd-90747bb0b5f5.png">

**Comment by DylanCaiCoding** [comment]
as 抽风了？aar 都下载了不应该找不到

**Comment by conscious01** [comment]
确实是AS 抽风了
因为最近在封装一个既能使用ButterKnife 又能使用Viewbinding 的base库，使用的是4.0.1版本的AS，所以看不到kotlin的代码
运行一下就可以了
