### ISSUE TITLE
implementation "com.github.CymChad:BaseRecyclerViewAdapterHelper:$brvahVersion"

### ISSUE THREAD

**Issue by ljphawk** [DylanCaiCoding/ViewBindingKTX#57]
2.0.6版本  ，是不是应该改成  api "com.github.CymChad:BaseRecyclerViewAdapterHelper:$brvahVersion"

**Comment by DylanCaiCoding** [comment]
个人觉得没必要省一行依赖，而且个人只是给出了一点 ViewBinding 的补充，只有几行代码。

**Comment by ljphawk** [comment]
// 如果使用了 viewbinding-nonreflection-ktx 可以不添加
implementation 'com.github.DylanCaiCoding.ViewBindingKTX:viewbinding-brvah:2.1.0'

你文档这么写的

**Comment by ljphawk** [comment]
曲解你文档这句注释的意思了 
// 如果使用了 viewbinding-nonreflection-ktx 可以不添加
