### ISSUE TITLE
混淆之后报错，配置了混淆规则也没用

### ISSUE THREAD

**Issue by jiqianwen** [DylanCaiCoding/ViewBindingKtx#6]
-keepclassmembers class * implements androidx.viewbinding.ViewBinding {
  public static ** inflate(...);
  public static ** bind(***);
}
按照上面这样配置会闪退报错 There is no generic of ViewBinding

-keep class * implements androidx.viewbinding.ViewBinding {
  *;
}
这样配置就正常了，但是这样所有类都不混淆了。。。

**Comment by DylanCaiCoding** [comment]
建议改成：

```
-keepclassmembers class * implements androidx.viewbinding.ViewBinding {
  public static * inflate(android.view.LayoutInflater);
  public static * inflate(android.view.LayoutInflater, android.view.ViewGroup, boolean);
  public static * bind(android.view.View);
}
```

新版本不用再自己配置混淆代码，你可以先试下测试版，以下可以根据自己的需要进行选择。用法上也有所变化，统一改成了 by binding()，迟点发正式版会更新文档。

```
dependencies {
    implementation 'com.dylanc:viewbinding-ktx:1.1.0-alpha' 
    implementation 'com.dylanc:viewbinding-nonreflection-ktx:1.1.0-alpha'
    implementation 'com.dylanc:viewbinding-base-ktx:1.1.0-alpha'
}
```
