### ISSUE TITLE
按照最新的混淆规则混淆之后，依旧还是同样的闪退报错

### ISSUE THREAD

**Issue by jiqianwen** [DylanCaiCoding/ViewBindingKtx#7]
求解，最新的alpha版本是不是ViewBindingUtil没有了

**Comment by DylanCaiCoding** [comment]
我测了混淆没有问题哦。

抱歉刚刚测了下 alpha 版还不是最新的代码，我晚上发个 alpha2 版本。ViewBindingUtil 在 Java 封装基类的时候才用到，所以拆开放在含 viewbinding-base-ktx 的依赖里。

**Comment by jiqianwen** [comment]
混淆我改成下面这样就可以了
-keep class * implements androidx.viewbinding.ViewBinding {
  public static * inflate(android.view.LayoutInflater);
  public static * inflate(android.view.LayoutInflater, android.view.ViewGroup, boolean);
  public static * bind(android.view.View);
}
我依赖了com.dylanc:viewbinding-base-ktx:1.1.0-alpha 但是本地并没有成功引用
![QQ图片20210120165946](https://user-images.githubusercontent.com/26268908/105151432-eef4fe80-5b40-11eb-9cc2-3dfb54fc5fc7.png)

**Comment by DylanCaiCoding** [comment]
先在 build.gradle 加个 maven url，我忘记发布到 jcenter 了。

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/dylancai/maven' }
    }
}
```

**Comment by jiqianwen** [comment]
了解，感谢

**Comment by DylanCaiCoding** [comment]
已发 alpha2 版本，maven url 可以去掉了。

```
dependencies {
    implementation 'com.dylanc:viewbinding-ktx:1.1.0-alpha2' 
    implementation 'com.dylanc:viewbinding-nonreflection-ktx:1.1.0-alpha2'
    implementation 'com.dylanc:viewbinding-base-ktx:1.1.0-alpha2'
    implementation 'com.dylanc:viewbinding-brvah-ktx:1.1.0-alpha2' 
}
```
